/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.mavenproject1;

import java.awt.Image;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author lakshhkhatri
 */
public class DidYouGuess5 extends javax.swing.JFrame {

    /**
     * Creates new form DidYouGuess5
     */
    ArrayList gameQuesAndOptions;
    ArrayList<Boolean> guessed;
    Client client;

    public DidYouGuess5(ArrayList gameQuesAndOptions, Client client) {
        this.setVisible(true);
        initComponents();
        this.gameQuesAndOptions = gameQuesAndOptions;
        this.client = client;
        guessed = new ArrayList();
        setImages();
    }

    public void setImages() {

        ArrayList fullQ = (ArrayList) gameQuesAndOptions.get(0);
        String imageFileName = "/Users/lakshhkhatri/NetBeansProjects/mavenproject1/src/main/java/com/mycompany/mavenproject1/flagsInFolder/" + fullQ.get(0);
        imageField2.setIcon(new ImageIcon(new ImageIcon(imageFileName).getImage().getScaledInstance(imageField2.getWidth(), imageField2.getHeight(), Image.SCALE_SMOOTH)));
        
        fullQ = (ArrayList) gameQuesAndOptions.get(1);
        imageFileName = "/Users/lakshhkhatri/NetBeansProjects/mavenproject1/src/main/java/com/mycompany/mavenproject1/flagsInFolder/" + fullQ.get(0);
        imageField3.setIcon(new ImageIcon(new ImageIcon(imageFileName).getImage().getScaledInstance(imageField2.getWidth(), imageField2.getHeight(), Image.SCALE_SMOOTH)));
        
        fullQ = (ArrayList) gameQuesAndOptions.get(2);
        imageFileName = "/Users/lakshhkhatri/NetBeansProjects/mavenproject1/src/main/java/com/mycompany/mavenproject1/flagsInFolder/" + fullQ.get(0);
        imageField4.setIcon(new ImageIcon(new ImageIcon(imageFileName).getImage().getScaledInstance(imageField2.getWidth(), imageField2.getHeight(), Image.SCALE_SMOOTH)));
        
        fullQ = (ArrayList) gameQuesAndOptions.get(3);
        imageFileName = "/Users/lakshhkhatri/NetBeansProjects/mavenproject1/src/main/java/com/mycompany/mavenproject1/flagsInFolder/" + fullQ.get(0);
        imageField5.setIcon(new ImageIcon(new ImageIcon(imageFileName).getImage().getScaledInstance(imageField2.getWidth(), imageField2.getHeight(), Image.SCALE_SMOOTH)));
        
        fullQ = (ArrayList) gameQuesAndOptions.get(4);
        imageFileName = "/Users/lakshhkhatri/NetBeansProjects/mavenproject1/src/main/java/com/mycompany/mavenproject1/flagsInFolder/" + fullQ.get(0);
        imageField6.setIcon(new ImageIcon(new ImageIcon(imageFileName).getImage().getScaledInstance(imageField2.getWidth(), imageField2.getHeight(), Image.SCALE_SMOOTH)));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        imageField2 = new javax.swing.JLabel();
        imageField3 = new javax.swing.JLabel();
        jCheckBoxTwo = new javax.swing.JCheckBox();
        jCheckBoxOne = new javax.swing.JCheckBox();
        jCheckBoxThree = new javax.swing.JCheckBox();
        imageField4 = new javax.swing.JLabel();
        imageField5 = new javax.swing.JLabel();
        jCheckBoxFour = new javax.swing.JCheckBox();
        imageField6 = new javax.swing.JLabel();
        jCheckBoxFive = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Did You Guess?");

        jLabel2.setText("Please indicate the question(s) for which you guessed ");

        jCheckBoxTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxTwoActionPerformed(evt);
            }
        });

        jCheckBoxOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxOneActionPerformed(evt);
            }
        });

        jCheckBoxThree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxThreeActionPerformed(evt);
            }
        });

        jCheckBoxFour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxFourActionPerformed(evt);
            }
        });

        jCheckBoxFive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxFiveActionPerformed(evt);
            }
        });

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon("/Users/lakshhkhatri/Downloads/Untitled design (3).png")); // NOI18N
        jLabel4.setText("jLabel4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jCheckBoxFour))
            .addGroup(layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(jCheckBoxFive))
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jCheckBoxOne))
            .addGroup(layout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addComponent(imageField3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(jCheckBoxTwo))
            .addGroup(layout.createSequentialGroup()
                .addGap(286, 286, 286)
                .addComponent(imageField4, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel2))
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(imageField2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(320, 320, 320)
                .addComponent(jCheckBoxThree))
            .addGroup(layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(jLabel3))
            .addGroup(layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(jLabel1))
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(imageField5, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addComponent(imageField6, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(280, 280, 280)
                .addComponent(jCheckBoxFour))
            .addGroup(layout.createSequentialGroup()
                .addGap(280, 280, 280)
                .addComponent(jCheckBoxFive))
            .addGroup(layout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(jCheckBoxOne))
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(imageField3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(jCheckBoxTwo))
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(imageField4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel2))
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(imageField2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(jCheckBoxThree))
            .addGroup(layout.createSequentialGroup()
                .addGap(329, 329, 329)
                .addComponent(jButton1))
            .addGroup(layout.createSequentialGroup()
                .addGap(364, 364, 364)
                .addComponent(jLabel3))
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1))
            .addGroup(layout.createSequentialGroup()
                .addGap(206, 206, 206)
                .addComponent(imageField5, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(206, 206, 206)
                .addComponent(imageField6, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBoxTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxTwoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxTwoActionPerformed

    private void jCheckBoxOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxOneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxOneActionPerformed

    private void jCheckBoxThreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxThreeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxThreeActionPerformed

    private void jCheckBoxFourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxFourActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxFourActionPerformed

    private void jCheckBoxFiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxFiveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxFiveActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        String encodedGuessData = "";
        
        guessed.add(jCheckBoxOne.isSelected());
        guessed.add(jCheckBoxTwo.isSelected());
        guessed.add(jCheckBoxThree.isSelected());
        guessed.add(jCheckBoxFour.isSelected());
        guessed.add(jCheckBoxFive.isSelected());
        
        System.out.println(jCheckBoxOne.isSelected());
        System.out.println(jCheckBoxTwo.isSelected());
        System.out.println(jCheckBoxThree.isSelected());
        System.out.println(jCheckBoxFour.isSelected());
        System.out.println(jCheckBoxFive.isSelected());
        
        for (Boolean guessOrNot : guessed) { 
            if (guessOrNot == true) { 
                encodedGuessData += "true,";
            } else {
                encodedGuessData += "false,";
            }
        }
        jButton1.setEnabled(false);
        jLabel3.setText("Your responses have been submitted.");
        
        
        try {
            client.sendData(encodedGuessData);
            System.out.println("guess data sent.");
            
            // will need to send indv correct also
        } catch (IOException ex) {
            Logger.getLogger(DidYouGuess5.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imageField2;
    private javax.swing.JLabel imageField3;
    private javax.swing.JLabel imageField4;
    private javax.swing.JLabel imageField5;
    private javax.swing.JLabel imageField6;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBoxFive;
    private javax.swing.JCheckBox jCheckBoxFour;
    private javax.swing.JCheckBox jCheckBoxOne;
    private javax.swing.JCheckBox jCheckBoxThree;
    private javax.swing.JCheckBox jCheckBoxTwo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
