/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.mavenproject1;

/**
 *
 * @author lakshhkhatri
 */
public class Podium extends javax.swing.JFrame {

    /**
     * Creates new form Podium
     */
    
    public Podium(String firstPlace, String secondPlace) {
        initComponents();
        this.setVisible(true);
        
        firstLabel.setText(firstPlace);
        secondLabel.setText(secondPlace);
        thirdLable.setText(" ");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        firstLabel = new javax.swing.JLabel();
        secondLabel = new javax.swing.JLabel();
        thirdLable = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        firstLabel.setText("First");

        secondLabel.setText("Second");

        thirdLable.setText("Third");

        jLabel2.setIcon(new javax.swing.ImageIcon("/Users/lakshhkhatri/Downloads/Untitled design (4).png")); // NOI18N
        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(secondLabel)
                .addGap(205, 205, 205)
                .addComponent(thirdLable))
            .addGroup(layout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(firstLabel))
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(secondLabel))
            .addGroup(layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(thirdLable))
            .addGroup(layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(firstLabel))
            .addComponent(jLabel2)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel firstLabel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel secondLabel;
    private javax.swing.JLabel thirdLable;
    // End of variables declaration//GEN-END:variables
}
